"""Unit tests for app/usage/report.py -- the Markdown summary carries
every section, the numbers the page shows, and renders cleanly with
the parts a fresh deployment doesn't have yet."""
from datetime import datetime, timezone

from app.usage.report import render_markdown

SINCE = datetime(2026, 9, 1, tzinfo=timezone.utc)
UNTIL = datetime(2026, 9, 21, tzinfo=timezone.utc)

USAGE = {
    "totals": {"events": 500, "active_users": 3, "sessions": 12, "avg_session_ms": 754_000, "errors": 2},
    "tasks": {"annotate": {"count": 4, "median_ms": 600_000, "mean_ms": 700_000}, "review": {"count": 2, "median_ms": 120_000, "mean_ms": 150_000}},
    "friction": {
        "idle_share": 0.12,
        "by_screen": [
            {"route": "/studies", "score": 42, "views": 30, "clicks": 60, "bounces": 9, "bounce_rate": 0.3, "returns": 3, "back_rate": 0.1, "dead_clicks": 6, "dead_rate": 0.1, "rage_bursts": 1, "errors": 0},
            {"route": "/viewer/:id", "score": 5, "views": 12, "clicks": 300, "bounces": 0, "bounce_rate": 0.0, "returns": 0, "back_rate": 0.0, "dead_clicks": 15, "dead_rate": 0.05, "rage_bursts": 0, "errors": 2},
        ],
    },
    "users": [{"user_id": "u1", "username": "dr-test", "sessions": 8, "total_ms": 3_600_000, "avg_dwell_ms": 45_000, "back_and_forth": 0.2, "annotated": 4, "reviewed": 0, "errors": 2}],
}
PIPELINE = {
    "legs": {"annotation": {"queue": {"median_ms": 300_000, "count": 4}, "work": {"median_ms": 600_000, "count": 4}}, "review": {"queue": {"median_ms": 60_000, "count": 2}, "work": {"median_ms": 120_000, "count": 2}}},
    "bottlenecks": [{"card_id": "c", "card_type": "annotation", "case_id": "x", "case_title": "CT 7", "assignee": "dr-test", "kind": "queue", "waiting_ms": 10 * 86_400_000, "baseline_ms": None, "flagged": True}],
    "assignee_load": [],
}
FINDINGS = [
    {"id": "bottlenecks.flagged", "severity": "critical", "title": "1 case is stuck far longer than usual", "detail": "CT 7 has waited 10d.", "tab": "friction", "evidence": {}},
    {"id": "learning.faster.u1.annotation", "severity": "good", "title": "dr-test got 40% faster at annotation", "detail": "…", "tab": "people", "evidence": {}},
]
LEARNING = [
    {"actor_id": "u1", "username": "dr-test", "card_type": "annotation", "week": 0, "median_ms": 900_000, "count": 2},
    {"actor_id": "u1", "username": "dr-test", "card_type": "annotation", "week": 2, "median_ms": 540_000, "count": 2},
]


def test_report_has_every_section_and_the_headline_numbers():
    md = render_markdown(SINCE, UNTIL, USAGE, PIPELINE, FINDINGS, LEARNING)
    assert md.startswith("# Usage report · 2026-09-01 00:00 – 2026-09-21 00:00")
    for heading in ("## Findings", "## Headline numbers", "## Cycle time", "## Bottlenecks", "## Screens by friction", "## People", "## Learning curve"):
        assert heading in md, heading
    assert "- [!!] **1 case is stuck far longer than usual** — CT 7 has waited 10d." in md
    assert "- [+] **dr-test got 40% faster at annotation**" in md
    assert "| Active people | 3 |" in md and "| Median time to annotate | 10m 00s (4 cases) |" in md
    assert "| Friction score (0–100) | 31 |" in md  # (42*30 + 5*12) / 42
    assert "| Being annotated | 10m 00s | 4 |" in md
    assert "| CT 7 | annotation | dr-test | someone to start | 240h 00m |" in md
    assert "| /studies | 42 | 30 | 30% | 10% | 10% | 1 | 0 |" in md
    assert "| dr-test | 8 | 1h 00m | 45s | 20% | 4 | 0 | 2 |" in md
    assert "| dr-test | annotation | week 0: 15m 00s | week 2: 9m 00s |" in md
    assert md.rstrip().endswith("_Generated by VoxelLabel · Usage. Patient data is never recorded._")


def test_report_renders_without_pipeline_or_learning_data():
    md = render_markdown(SINCE, UNTIL, {**USAGE, "friction": {"idle_share": 0.0, "by_screen": []}, "users": []}, None, [], None)
    assert "## Cycle time" not in md and "## Learning curve" not in md
    assert "## Findings\n\n_none_" in md
    assert "## Screens by friction\n\n_none_" in md
    assert "| Friction score (0–100) | – |" in md
