"""Unit tests for app/usage/report.py -- the Markdown summary carries
every section, the numbers the page shows, and renders cleanly with
the parts a fresh deployment doesn't have yet."""
from datetime import datetime, timezone

from app.usage.report import render_markdown

SINCE = datetime(2026, 9, 1, tzinfo=timezone.utc)
UNTIL = datetime(2026, 9, 21, tzinfo=timezone.utc)

USAGE = {
    "totals": {"events": 500, "active_users": 3, "sessions": 12, "avg_session_ms": 754_000, "errors": 2},
    "tasks": {"annotate": {"count": 4, "median_ms": 600_000, "mean_ms": 700_000}, "review": {"count": 2, "median_ms": 120_000, "mean_ms": 150_000}},
    "effort": {
        "annotation": {"cases": 4, "active_median_ms": 600_000, "sittings_median": 1, "undos_per_case": 2.0, "first_input_median_ms": None, "first_input_count": 0},
        "review": {"cases": 2, "active_median_ms": 120_000, "sittings_median": 1, "undos_per_case": 0.0, "first_input_median_ms": None, "first_input_count": 0},
        "all": {"cases": 6, "active_median_ms": 300_000, "sittings_median": 1, "undos_per_case": 1.3, "first_input_median_ms": 8_000, "first_input_count": 6},
    },
    "basis": {"events": 900, "people": 3, "sessions": 12, "not_counted": 1, "admins_left_out": True},
    "friction": {
        "idle_share": 0.12,
        "by_screen": [
            {"route": "/studies", "score": 42, "views": 30, "clicks": 60, "bounces": 9, "bounce_rate": 0.3, "returns": 3, "back_rate": 0.1, "dead_clicks": 6, "dead_rate": 0.1, "rage_bursts": 1, "errors": 0},
            {"route": "/viewer/:id", "score": 5, "views": 12, "clicks": 300, "bounces": 0, "bounce_rate": 0.0, "returns": 0, "back_rate": 0.0, "dead_clicks": 15, "dead_rate": 0.05, "rage_bursts": 0, "errors": 2},
        ],
    },
    "users": [{"user_id": "u1", "username": "dr-test", "sessions": 8, "total_ms": 3_600_000, "avg_dwell_ms": 45_000, "back_and_forth": 0.2, "annotated": 4, "reviewed": 0, "errors": 2}],
}
PIPELINE = {
    "legs": {"annotation": {"queue": {"median_ms": 300_000, "count": 4}, "work": {"median_ms": 600_000, "count": 4}}, "review": {"queue": {"median_ms": 60_000, "count": 2}, "work": {"median_ms": 120_000, "count": 2}}},
    "bottlenecks": [{"card_id": "c", "card_type": "annotation", "case_id": "x", "case_title": "CT 7", "assignee": "dr-test", "kind": "queue", "waiting_ms": 10 * 86_400_000, "baseline_ms": None, "flagged": True}],
    "assignee_load": [],
}
FINDINGS = [
    {"id": "bottlenecks.flagged", "severity": "critical", "title": "1 case is stuck far longer than usual", "detail": "CT 7 has waited 10d.", "tab": "friction", "evidence": {}},
    {"id": "learning.faster.u1.annotation", "severity": "good", "title": "dr-test got 40% faster at annotation", "detail": "…", "tab": "people", "evidence": {}},
]
LEARNING = [
    {"actor_id": "u1", "username": "dr-test", "card_type": "annotation", "week": 0, "median_ms": 900_000, "count": 2},
    {"actor_id": "u1", "username": "dr-test", "card_type": "annotation", "week": 2, "median_ms": 540_000, "count": 2},
]


def test_report_has_every_section_and_the_headline_numbers():
    md = render_markdown(SINCE, UNTIL, USAGE, PIPELINE, FINDINGS, LEARNING)
    assert md.startswith("# Usage report · 2026-09-01 00:00 – 2026-09-21 00:00")
    for heading in ("## Findings", "## Headline numbers", "## Cycle time", "## Bottlenecks", "## Screens by friction", "## People", "## Learning curve"):
        assert heading in md, heading
    assert "- [!!] **1 case is stuck far longer than usual** — CT 7 has waited 10d." in md
    assert "- [+] **dr-test got 40% faster at annotation**" in md
    assert "| Active people | 3 |" in md and "| Hands-on time per case, annotating | 10m 00s (4 cases) |" in md
    assert "| Time to first action in the viewer | 8s (6 openings) |" in md
    assert "_Based on 900 events from 3 people in 12 sessions; 1 accounts not counted (admins and test accounts)._" in md
    assert "| Friction score (0–100) | 31 |" in md  # (42*30 + 5*12) / 42
    assert "| Annotating (opened → submitted) | 10m 00s | 4 |" in md
    assert "| CT 7 | annotation | dr-test | an annotator to start | 240h 00m |" in md
    assert "| /studies | 42 | 30 | 30% | 10% | 10% | 1 | 0 |" in md
    assert "| dr-test | 8 | 1h 00m | 45s | 20% | 4 | 0 | 2 |" in md
    assert "| dr-test | annotation | week 0: 15m 00s | week 2: 9m 00s |" in md
    assert md.rstrip().endswith("_Generated by VoxelLabel · Usage. Patient data is never recorded._")


def test_report_renders_without_pipeline_or_learning_data():
    md = render_markdown(SINCE, UNTIL, {**USAGE, "friction": {"idle_share": 0.0, "by_screen": []}, "users": []}, None, [], None)
    assert "## Cycle time" not in md and "## Learning curve" not in md
    assert "## Findings\n\n_none_" in md
    assert "## Screens by friction\n\n_none_" in md
    assert "| Friction score (0–100) | – |" in md


def test_report_carries_releases_cases_reasons_and_performance():
    extra = {
        **USAGE,
        "releases": [{"app": "viewer", "version": "0.1.0+a", "first_seen": "2026-09-02T10:00:00+00:00", "people": 2, "cases": 5, "active_median_ms": 90_000, "first_input_median_ms": 4_000, "no_response_rate": 0.1, "friction_score": 12}],
        "complexity": {"cases": 5, "per_object_median_ms": 30_000, "drivers": [{"factor": "objects", "label": "objects drawn", "r": 0.8, "n": 5}]},
        "ratings": {"count": 4, "mean": 3.2, "distribution": {}},
        "reject_reasons": {"total": 3, "reasons": [{"reason": "boundary", "count": 3, "share": 1.0}]},
        "performance": [{"endpoint": "/volume", "calls": 10, "mean_ms": 1200, "max_ms": 3000, "slow_share": 0.3, "failure_rate": 0.0}],
    }
    md = render_markdown(SINCE, UNTIL, extra, PIPELINE, FINDINGS, LEARNING)
    assert "| viewer | 0.1.0+a | 2026-09-02 10:00 | 2 | 5 | 1m 30s | 4s | 10% | 12 |" in md
    assert "median hands-on time per object 30s. Moves with hands-on time: objects drawn (r = 0.8)." in md
    assert "Felt difficulty: 3.2 of 5 from 4 answers." in md
    assert "| boundary | 3 | 100% |" in md and "| /volume | 10 | 1s | 3s | 30% | 0% |" in md
