"""initial schema

Revision ID: 0e59bfd285e6
Revises: 
Create Date: 2026-08-14 18:24:58.279756
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0e59bfd285e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('json_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('immutable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deidentification_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pseudonym_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pseudonym_id')
    )
    op.create_table('deidentification_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('dicom_tag', sa.String(length=32), nullable=False),
    sa.Column('action', sa.Enum('KEEP', 'REMOVE', 'REPLACE_FIXED', 'HASH', name='deidentificationaction'), nullable=False),
    sa.Column('replacement_value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['deidentification_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_identity_map',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('external_id_hash', sa.String(length=128), nullable=False),
    sa.Column('access_restricted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('external_id_hash')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deidentification_profile_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deidentification_profile_id'], ['deidentification_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('annotator_id', sa.String(length=255), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='annotationstatus'), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_type IN ('instance','series','study')", name='ck_annotation_target_type'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['annotations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['annotation_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_memberships',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DATA_MANAGER', 'ANNOTATOR', 'REVIEWER', 'VIEWER', name='projectrole'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('studies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('study_instance_uid', sa.String(length=128), nullable=False),
    sa.Column('study_date', sa.Date(), nullable=True),
    sa.Column('modality', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_instance_uid')
    )
    op.create_table('annotation_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('annotation_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_snapshot_items',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('annotation_version_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_version_id'], ['annotations.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['dataset_snapshots.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('snapshot_id', 'study_id', 'annotation_version_id')
    )
    op.create_table('series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('series_instance_uid', sa.String(length=128), nullable=False),
    sa.Column('series_number', sa.Integer(), nullable=True),
    sa.Column('body_part', sa.String(length=64), nullable=True),
    sa.Column('series_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_instance_uid')
    )
    op.create_table('instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('sop_instance_uid', sa.String(length=128), nullable=False),
    sa.Column('instance_number', sa.Integer(), nullable=True),
    sa.Column('object_storage_key', sa.String(length=512), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('pixel_spacing', postgresql.ARRAY(sa.Numeric()), nullable=True),
    sa.Column('window_center', sa.Numeric(), nullable=True),
    sa.Column('window_width', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sop_instance_uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instances')
    op.drop_table('series')
    op.drop_table('dataset_snapshot_items')
    op.drop_table('annotation_reviews')
    op.drop_table('studies')
    op.drop_table('project_memberships')
    op.drop_table('annotations')
    op.drop_table('projects')
    op.drop_table('patient_identity_map')
    op.drop_table('deidentification_rules')
    op.drop_table('patients')
    op.drop_table('deidentification_profiles')
    op.drop_table('dataset_snapshots')
    op.drop_table('audit_log')
    op.drop_table('annotation_types')
    # ### end Alembic commands ###
