"""add project cover image

Revision ID: 2e295fd26b10
Revises: d9971e5ac0c0
Create Date: 2026-08-15 13:06:58.499765
"""
from alembic import op
import sqlalchemy as sa


revision = '2e295fd26b10'
down_revision = 'd9971e5ac0c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('cover_image_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'cover_image_key')
    # ### end Alembic commands ###
