"""add case summary fields and instance thumbnail

Revision ID: 86302299d2cd
Revises: 2e295fd26b10
Create Date: 2026-08-15 14:10:49.397350
"""
from alembic import op
import sqlalchemy as sa


revision = '86302299d2cd'
down_revision = '2e295fd26b10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('cases', sa.Column('type', sa.String(length=64), nullable=True))
    op.add_column('cases', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('cases', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('instances', sa.Column('thumbnail_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances', 'thumbnail_key')
    op.drop_column('cases', 'comment')
    op.drop_column('cases', 'title')
    op.drop_column('cases', 'type')
    op.drop_column('cases', 'date')
    # ### end Alembic commands ###
