"""add workflow board cards and edges

Revision ID: 8b0926a7d51c
Revises: f3a91c7b2e04
Create Date: 2026-08-21 13:23:15.391077
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8b0926a7d51c'
down_revision = 'f3a91c7b2e04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DATASET', 'SPLIT', 'FILTER', 'ANNOTATION', 'REVIEW', 'UNION', 'NOTE', 'MILESTONE', name='workflowcardtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_case_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('height IS NULL OR height > 0', name='ck_workflow_card_height_positive'),
    sa.CheckConstraint('width IS NULL OR width > 0', name='ck_workflow_card_width_positive'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_cards_study_id'), 'workflow_cards', ['study_id'], unique=False)
    op.create_table('workflow_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('source_card_id', sa.UUID(), nullable=False),
    sa.Column('source_handle', sa.String(length=64), nullable=False),
    sa.Column('target_card_id', sa.UUID(), nullable=False),
    sa.Column('target_handle', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_card_id'], ['workflow_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_card_id'], ['workflow_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_edges_study_id'), 'workflow_edges', ['study_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_edges_study_id'), table_name='workflow_edges')
    op.drop_table('workflow_edges')
    op.drop_index(op.f('ix_workflow_cards_study_id'), table_name='workflow_cards')
    op.drop_table('workflow_cards')
    # ### end Alembic commands ###
    # Not auto-generated: dropping the table does not drop the Postgres
    # enum type `create_table` implicitly created for the `type` column.
    op.execute("DROP TYPE workflowcardtype")
