"""case-centric data model: add cases, clinical data items, tags, consents

Revision ID: d9971e5ac0c0
Revises: 0e59bfd285e6
Create Date: 2026-08-15 11:56:08.929514
"""
from alembic import op
import sqlalchemy as sa


revision = 'd9971e5ac0c0'
down_revision = '0e59bfd285e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('accession_number', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_data_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('object_storage_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinical_data_item_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('GRANTED', 'REVOKED', name='consentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinical_data_item_id'], ['clinical_data_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinical_data_item_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['clinical_data_item_id'], ['clinical_data_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # case_id starts nullable so existing rows can be backfilled below --
    # autogenerate can't know that a NOT NULL column needs a data migration
    # first, since project_id/patient_id already have values for every
    # existing study.
    op.add_column('studies', sa.Column('case_id', sa.UUID(), nullable=True))

    # One Case per distinct (project_id, patient_id) pair already
    # referenced by an existing study; accession_number is left null since
    # there was no equivalent concept before this migration.
    op.execute("""
        INSERT INTO cases (id, project_id, patient_id, created_at)
        SELECT gen_random_uuid(), project_id, patient_id, now()
        FROM (SELECT DISTINCT project_id, patient_id FROM studies) AS distinct_pairs
    """)
    op.execute("""
        UPDATE studies
        SET case_id = cases.id
        FROM cases
        WHERE studies.project_id = cases.project_id
          AND studies.patient_id = cases.patient_id
    """)

    op.alter_column('studies', 'case_id', nullable=False)
    op.drop_constraint(op.f('studies_project_id_fkey'), 'studies', type_='foreignkey')
    op.drop_constraint(op.f('studies_patient_id_fkey'), 'studies', type_='foreignkey')
    op.create_foreign_key(None, 'studies', 'cases', ['case_id'], ['id'])
    op.drop_column('studies', 'project_id')
    op.drop_column('studies', 'patient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('studies', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True))

    op.execute("""
        UPDATE studies
        SET project_id = cases.project_id, patient_id = cases.patient_id
        FROM cases
        WHERE studies.case_id = cases.id
    """)

    op.alter_column('studies', 'project_id', nullable=False)
    op.alter_column('studies', 'patient_id', nullable=False)
    op.drop_constraint(None, 'studies', type_='foreignkey')
    op.create_foreign_key(op.f('studies_patient_id_fkey'), 'studies', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('studies_project_id_fkey'), 'studies', 'projects', ['project_id'], ['id'])
    op.drop_column('studies', 'case_id')
    op.drop_table('tags')
    op.drop_table('consents')
    op.drop_table('clinical_data_items')
    op.drop_table('cases')
    # ### end Alembic commands ###
