"""rename Project -> Study (RBAC container) and old Study -> ImagingStudy

Revision ID: f3a91c7b2e04
Revises: 86302299d2cd
Create Date: 2026-08-15 18:00:00.000000

Hand-written (not autogenerated): renames confuse Alembic's autogenerate
diffing, which would otherwise emit a drop+create pair and lose data. All
operations here are metadata-only renames -- no data is copied or lost.

The DICOM "Study" entity is renamed to "ImagingStudy" first, to free up
the name "Study" for what used to be called "Project" (the top-level,
admin-created RBAC container that scopes many Cases). See
ARCHITECTURE.md and the shared_models.models module docstrings for the
distinction between the two.
"""
from alembic import op


revision = 'f3a91c7b2e04'
down_revision = '86302299d2cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Old DICOM "Study" -> "ImagingStudy" (must happen before "projects"
    # claims the "studies" table name).
    op.rename_table('studies', 'imaging_studies')
    op.alter_column('series', 'study_id', new_column_name='imaging_study_id')
    op.alter_column('dataset_snapshot_items', 'study_id', new_column_name='imaging_study_id')

    # "Project" -> "Study" (RBAC container).
    op.rename_table('projects', 'studies')
    op.rename_table('project_memberships', 'study_memberships')
    op.alter_column('study_memberships', 'project_id', new_column_name='study_id')
    op.alter_column('cases', 'project_id', new_column_name='study_id')
    op.alter_column('annotations', 'project_id', new_column_name='study_id')

    op.execute("ALTER TYPE projectrole RENAME TO studyrole")


def downgrade() -> None:
    op.execute("ALTER TYPE studyrole RENAME TO projectrole")

    op.alter_column('annotations', 'study_id', new_column_name='project_id')
    op.alter_column('cases', 'study_id', new_column_name='project_id')
    op.alter_column('study_memberships', 'study_id', new_column_name='project_id')
    op.rename_table('study_memberships', 'project_memberships')
    op.rename_table('studies', 'projects')

    op.alter_column('dataset_snapshot_items', 'imaging_study_id', new_column_name='study_id')
    op.alter_column('series', 'imaging_study_id', new_column_name='study_id')
    op.rename_table('imaging_studies', 'studies')
