"""Fails when the ORM models and the migrated schema disagree (I-01).

The integration tests build their database from the models
(Base.metadata.create_all), production from the migrations. Anything that
exists only in the migrations -- an index, a unique constraint -- is then
missing from every test run, and the next autogenerated migration would
propose dropping it. Run against an empty database after
`alembic upgrade head`:

    DATABASE_URL=... python check_models_match.py
"""
import sys

from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext
from shared_models.database import engine
from shared_models.models import Base


def main() -> int:
    with engine.connect() as conn:
        diff = compare_metadata(MigrationContext.configure(conn), Base.metadata)
    # server-default / comment noise is not a structural difference
    diff = [d for d in diff if not (isinstance(d, tuple) and d[0] in ("modify_default", "modify_comment"))]
    for d in diff:
        print(d)
    print(f"{len(diff)} difference(s) between the models and the migrated schema")
    return 1 if diff else 0


if __name__ == "__main__":
    sys.exit(main())
